# Generated by Django 4.2.1 on 2023-05-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0003_classe_module_etudiant_enseignement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignement',
            name='nom_eng',
        ),
    ]
