# Generated by Django 4.2.1 on 2023-05-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0004_remove_enseignement_nom_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignement',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Classe', to='ABS.classe'),
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Module', to='ABS.module'),
        ),
        migrations.AlterField(
            model_name='enseignement',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Professeur', to='ABS.professeur'),
        ),
    ]
