# Generated by Django 4.2.1 on 2023-05-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0005_alter_enseignement_classe_alter_enseignement_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='mote_pass',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
