# Generated by Django 4.2.1 on 2023-05-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0006_professeur_mote_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='professeur',
            name='mote_pass',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.CreateModel(
            name='Abssence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(choices=[('P', 'Présent'), ('A', 'Absent')], max_length=1)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='ABS.etudiant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seance', to='ABS.seance')),
            ],
        ),
    ]
