# Generated by Django 4.2.1 on 2023-05-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0008_seance_enseignement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fillier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef', to='ABS.professeur')),
            ],
        ),
        migrations.AlterField(
            model_name='classe',
            name='fillier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillier', to='ABS.fillier'),
        ),
    ]
