# Generated by Django 4.2.1 on 2023-05-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0009_fillier_alter_classe_fillier'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(default='h', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='mote_pass',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
