# Generated by Django 4.2.1 on 2023-05-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0011_etudiant_numero_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillier',
            name='nom_comlaite',
            field=models.CharField(default='ik', max_length=100),
            preserve_default=False,
        ),
    ]
